// Atualizado em 04/10/2026. Pesquisas de intenção de voto para governador (cenário estimulado, 1º turno).
// Números copiados das divulgações oficiais (fontes em fonteUrl) — confira antes de publicar.
// Legislação (Res. TSE 23.600/2019): a divulgação precisa trazer instituto, período, entrevistas,
// margem de erro, nível de confiança, contratante e nº de registro — a página mostra no rodapé.
// tipo 'outro' = indecisos / brancos e nulos / outros (ícone genérico, sem partido).
// foto: nome do arquivo em fotos-pesquisa/ (sem foto = iniciais). Mais de 6 candidatos: os menores viram "OUTROS".
const _BN = (pct, nome = 'BRANCOS E NULOS') => ({ nome, pct, tipo: 'outro' });
const _IND = pct => ({ nome: 'INDECISOS', pct, tipo: 'outro' });

window.PESQUISAS = [
  // ---------------- PRESIDENTE (BRASIL) ----------------
  { id: 'datafolha-br-pres-2026-10-03', uf: 'br', creditoFotos: 'fotos: Wikimedia Commons (licenças Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'PRESIDENTE', local: 'BRASIL', turno: 'VOTOS VÁLIDOS', campo: '03/10/2026', entrevistas: '4.006',
    margem: '2 pontos', confianca: '95%', contratante: 'FOLHA DE S.PAULO E TV GLOBO', registro: 'BR-01708/2026',
    fonteUrl: 'https://www.dgabc.com.br/Noticia/4350626/datafolha-lula-tem-45-dos-votos-validos-e-flavio-bolsonaro-42-no-1-turno',
    itens: [
      { nome: 'LULA', partido: 'PT', pct: 45, foto: 'lula' },
      { nome: 'FLÁVIO BOLSONARO', partido: 'PL', pct: 42, foto: 'flavio-bolsonaro' },
      { nome: 'RONALDO CAIADO', partido: 'PSD', pct: 4, foto: 'ronaldo-caiado' },
      { nome: 'RENAN SANTOS', partido: 'MISSÃO', pct: 3, foto: 'renan-santos' },
      { nome: 'AUGUSTO CURY', partido: 'AVANTE', pct: 3, foto: 'augusto-cury' },
      { nome: 'ROMEU ZEMA', partido: 'NOVO', pct: 1 },
      { nome: 'SAMARA', partido: 'UP', pct: 0 },
      { nome: 'CLARIANA BARÃO', partido: 'DC', pct: 0 },
      { nome: 'EDMILSON COSTA', partido: 'PCB', pct: 0 },
      { nome: 'HERTZ DIAS', partido: 'PSTU', pct: 0 },
      { nome: 'RUI COSTA PIMENTA', partido: 'PCO', pct: 0 },
      { nome: 'VETERINÁRIO WILSON GRASSI', partido: 'DEMOCRATA', pct: 0 },
    ] },
  { id: 'quaest-br-pres-2026-10-03', uf: 'br', creditoFotos: 'fotos: Wikimedia Commons (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'PRESIDENTE', local: 'BRASIL', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '3.702',
    margem: '2 pontos', confianca: '95%', contratante: 'EDITORA GLOBO E TV GLOBO', registro: 'BR-02197/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-presidente-outubro-2026/',
    itens: [
      { nome: 'LULA', partido: 'PT', pct: 46, foto: 'lula' },
      { nome: 'FLÁVIO BOLSONARO', partido: 'PL', pct: 45, foto: 'flavio-bolsonaro' },
      { nome: 'AUGUSTO CURY', partido: 'AVANTE', pct: 3, foto: 'augusto-cury' },
      { nome: 'RONALDO CAIADO', partido: 'PSD', pct: 3, foto: 'ronaldo-caiado' },
      { nome: 'RENAN SANTOS', partido: 'MISSÃO', pct: 3, foto: 'renan-santos' },
      { nome: 'ROMEU ZEMA', partido: 'NOVO', pct: 0 },
      { nome: 'SAMARA', partido: 'UP', pct: 0 },
      { nome: 'CLARIANA BARÃO', partido: 'DC', pct: 0 },
      { nome: 'EDMILSON COSTA', partido: 'PCB', pct: 0 },
      { nome: 'HERTZ DIAS', partido: 'PSTU', pct: 0 },
      { nome: 'RUI COSTA PIMENTA', partido: 'PCO', pct: 0 },
      { nome: 'VETERINÁRIO WILSON GRASSI', partido: 'DEMOCRATA', pct: 0 },
    ] },

  // ---------------- CEARÁ ----------------
  { id: 'datafolha-ce-gov-2026-10-03', uf: 'ce', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'CEARÁ', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '1.560',
    margem: '2 pontos', confianca: '95%', contratante: 'O POVO', registro: 'CE-09234/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/datafolha-governador-senador-ceara-outubro-2026/',
    itens: [
      { nome: 'ELMANO DE FREITAS', partido: 'PT', pct: 50, foto: 'elmano' },
      { nome: 'CIRO GOMES', partido: 'PSDB', pct: 47, foto: 'ciro' },
      { nome: 'VERA LÚCIA', partido: 'NOVO', pct: 1, foto: 'vera' },
      { nome: 'DELEGADO HUGGO', partido: 'MISSÃO', pct: 1, foto: 'huggo' },
      { nome: 'ZÉ BATISTA', partido: 'PSTU', pct: 1, foto: 'tse-ce-ze-batista' },
    ] },
  { id: 'quaest-ce-gov-2026-10-03', uf: 'ce', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'CEARÁ', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '2.004',
    margem: '2 pontos', confianca: '95%', contratante: 'TV VERDES MARES', registro: 'CE-04790/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-ceara-outubro-2026/',
    itens: [
      { nome: 'ELMANO DE FREITAS', partido: 'PT', pct: 50, foto: 'elmano' },
      { nome: 'CIRO GOMES', partido: 'PSDB', pct: 49, foto: 'ciro' },
      { nome: 'DELEGADO HUGGO', partido: 'MISSÃO', pct: 1, foto: 'huggo' },
      { nome: 'DANILO SOARES', partido: 'DEMOCRATA', pct: 0, foto: 'danilo' },
      { nome: 'IERI BRAGA', partido: 'PCO', pct: 0, foto: 'tse-ce-ieri-braga' },
      { nome: 'SERLEY LEAL', partido: 'UP', pct: 0, foto: 'serley' },
      { nome: 'VERA LÚCIA', partido: 'NOVO', pct: 0, foto: 'vera' },
      { nome: 'ZÉ BATISTA', partido: 'PSTU', pct: 0, foto: 'tse-ce-ze-batista' },
    ] },

  // ---------------- SÃO PAULO ----------------
  { id: 'datafolha-sp-gov-2026-10-03', uf: 'sp', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'SÃO PAULO', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '2.520',
    margem: '2 pontos', confianca: '95%', contratante: 'TV GLOBO E FOLHA DE S.PAULO', registro: 'SP-09337/2026',
    fonteUrl: 'https://www.terra.com.br/noticias/eleicoes/pesquisas/pesquisa-datafolha-para-o-governo-de-sp-tarcisio-tem-60-em-votos-validos-haddad-35,ba8646a782141faa79f4708df81080eao09d8rq2.html',
    itens: [
      { nome: 'TARCÍSIO DE FREITAS', partido: 'REPUBLICANOS', pct: 60, foto: 'tarcisio-de-freitas' },
      { nome: 'FERNANDO HADDAD', partido: 'PT', pct: 35, foto: 'fernando-haddad' },
      { nome: 'VERA LÚCIA', partido: 'PSTU', pct: 2, foto: 'vera-lucia' },
      { nome: 'CARLOS MACHADO', partido: 'PCB', pct: 2, foto: 'tse-sp-carlos-machado' },
      { nome: 'VIVIAN MENDES', partido: 'UP', pct: 1, foto: 'tse-sp-vivian-mendes' },
      { nome: 'IZADORA DIAS', partido: 'PCO', pct: 1, foto: 'tse-sp-izadora-dias' },
    ] },
  { id: 'quaest-sp-gov-2026-10-03', uf: 'sp', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'SÃO PAULO', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '3.702',
    margem: '2 pontos', confianca: '95%', contratante: 'TV GLOBO E ELETROMIDIA', registro: 'SP-04726/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-sao-paulo-outubro-2026/',
    itens: [
      { nome: 'TARCÍSIO DE FREITAS', partido: 'REPUBLICANOS', pct: 60, foto: 'tarcisio-de-freitas' },
      { nome: 'FERNANDO HADDAD', partido: 'PT', pct: 36, foto: 'fernando-haddad' },
      { nome: 'VERA LÚCIA', partido: 'PSTU', pct: 2, foto: 'vera-lucia' },
      { nome: 'VIVIAN MENDES', partido: 'UP', pct: 2, foto: 'tse-sp-vivian-mendes' },
      { nome: 'CARLOS MACHADO', partido: 'PCB', pct: 0, foto: 'tse-sp-carlos-machado' },
      { nome: 'IZADORA DIAS', partido: 'PCO', pct: 0, foto: 'tse-sp-izadora-dias' },
    ] },

  // ---------------- RIO DE JANEIRO ----------------
  { id: 'datafolha-rj-gov-2026-10-03', uf: 'rj', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'RIO DE JANEIRO', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '2.010',
    margem: '2 pontos', confianca: '95%', contratante: 'FOLHA DE S.PAULO E REDE GLOBO', registro: 'RJ-01334/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/datafolha-governador-senador-rio-de-janeiro-outubro-2026-2/',
    itens: [
      { nome: 'EDUARDO PAES', partido: 'PSD', pct: 46, foto: 'eduardo-paes' },
      { nome: 'DOUGLAS RUAS', partido: 'PL', pct: 38, foto: 'douglas-ruas' },
      { nome: 'ANTHONY GAROTINHO', partido: 'REPUBLICANOS', pct: 7, foto: 'anthony-garotinho' },
      { nome: 'WILLIAM SIRI', partido: 'PSOL', pct: 4, foto: 'tse-rj-william-siri' },
      { nome: 'CORONEL BUSNELLO', partido: 'MISSÃO', pct: 2, foto: 'tse-rj-coronel-busnello' },
      { nome: 'ANDRÉ MARINHO', partido: 'NOVO', pct: 1, foto: 'tse-rj-andre-marinho' },
      { nome: 'CYRO GARCIA', partido: 'PSTU', pct: 1, foto: 'cyro-garcia' },
      { nome: 'JULIETE PANTOJA', partido: 'UP', pct: 1, foto: 'tse-rj-juliete' },
      { nome: 'LUAN MONTEIRO', partido: 'PCO', pct: 1, foto: 'tse-rj-luan-monteiro' },
    ] },
  { id: 'quaest-rj-gov-2026-10-03', uf: 'rj', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'RIO DE JANEIRO', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '3.204',
    margem: '2 pontos', confianca: '95%', contratante: 'TV GLOBO', registro: 'RJ-03032/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-rio-de-janeiro-outubro-2026/',
    itens: [
      { nome: 'EDUARDO PAES', partido: 'PSD', pct: 49, foto: 'eduardo-paes' },
      { nome: 'DOUGLAS RUAS', partido: 'PL', pct: 40, foto: 'douglas-ruas' },
      { nome: 'ANTHONY GAROTINHO', partido: 'REPUBLICANOS', pct: 6, foto: 'anthony-garotinho' },
      { nome: 'WILLIAM SIRI', partido: 'PSOL', pct: 3, foto: 'tse-rj-william-siri' },
      { nome: 'CORONEL BUSNELLO', partido: 'MISSÃO', pct: 1, foto: 'tse-rj-coronel-busnello' },
      { nome: 'ANDRÉ MARINHO', partido: 'NOVO', pct: 1, foto: 'tse-rj-andre-marinho' },
      { nome: 'CYRO GARCIA', partido: 'PSTU', pct: 0, foto: 'cyro-garcia' },
      { nome: 'JULIETE PANTOJA', partido: 'UP', pct: 0, foto: 'tse-rj-juliete' },
      { nome: 'LUAN MONTEIRO', partido: 'PCO', pct: 0, foto: 'tse-rj-luan-monteiro' },
    ] },

  // ---------------- MINAS GERAIS ----------------
  { id: 'datafolha-mg-gov-2026-10-03', uf: 'mg', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'MINAS GERAIS', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '2.010',
    margem: '2 pontos', confianca: '95%', contratante: 'TV GLOBO E FOLHA DE S.PAULO', registro: 'MG-06705/2026',
    fonteUrl: 'https://www.metropoles.com/minas-gerais/ultimo-datafolha-em-mg-traz-cleitinho-com-53-dos-votos-validos',
    itens: [
      { nome: 'CLEITINHO', partido: 'REPUBLICANOS', pct: 53, foto: 'cleitinho' },
      { nome: 'PATRUS ANANIAS', partido: 'PT', pct: 21, foto: 'patrus-ananias' },
      { nome: 'ALEXANDRE KALIL', partido: 'PDT', pct: 9, foto: 'alexandre-kalil' },
      { nome: 'MATEUS SIMÕES', partido: 'PSD', pct: 4, foto: 'mateus-simoes' },
      { nome: 'FLÁVIO ROSCOE', partido: 'PL', pct: 4, foto: 'tse-mg-flavio-roscoe' },
      { nome: 'GABRIEL', partido: 'MDB', pct: 3, foto: 'tse-mg-gabriel' },
      { nome: 'BEN MENDES', partido: 'MISSÃO', pct: 2, foto: 'tse-mg-ben-mendes' },
      { nome: 'HENRIQUE ÁREAS', partido: 'PCO', pct: 1, foto: 'tse-mg-henrique-areas' },
      { nome: 'RAFAEL DUDA', partido: 'PSTU', pct: 1, foto: 'tse-mg-rafael-duda' },
      { nome: 'PROFESSOR TÚLIO LOPES', partido: 'PCB', pct: 1, foto: 'tse-mg-professor-tulio-lopes' },
      { nome: 'INDIRA XAVIER', partido: 'UP', pct: 0, foto: 'tse-mg-indira-xavier' },
    ] },
  { id: 'quaest-mg-gov-2026-10-03', uf: 'mg', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'MINAS GERAIS', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '3.204',
    margem: '2 pontos', confianca: '95%', contratante: 'TV GLOBO', registro: 'MG-06889/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-minas-gerais-outubro-2026/',
    itens: [
      { nome: 'CLEITINHO', partido: 'REPUBLICANOS', pct: 54, foto: 'cleitinho' },
      { nome: 'PATRUS ANANIAS', partido: 'PT', pct: 23, foto: 'patrus-ananias' },
      { nome: 'ALEXANDRE KALIL', partido: 'PDT', pct: 10, foto: 'alexandre-kalil' },
      { nome: 'FLÁVIO ROSCOE', partido: 'PL', pct: 6, foto: 'tse-mg-flavio-roscoe' },
      { nome: 'MATEUS SIMÕES', partido: 'PSD', pct: 4, foto: 'mateus-simoes' },
      { nome: 'GABRIEL', partido: 'MDB', pct: 2, foto: 'tse-mg-gabriel' },
      { nome: 'BEN MENDES', partido: 'MISSÃO', pct: 1, foto: 'tse-mg-ben-mendes' },
      { nome: 'PROFESSOR TÚLIO LOPES', partido: 'PCB', pct: 0, foto: 'tse-mg-professor-tulio-lopes' },
      { nome: 'INDIRA XAVIER', partido: 'UP', pct: 0, foto: 'tse-mg-indira-xavier' },
      { nome: 'HENRIQUE ÁREAS', partido: 'PCO', pct: 0, foto: 'tse-mg-henrique-areas' },
      { nome: 'RAFAEL DUDA', partido: 'PSTU', pct: 0, foto: 'tse-mg-rafael-duda' },
    ] },

  // ---------------- AMAZONAS ----------------
  { id: 'quaest-am-gov-2026-10-03', uf: 'am', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'AMAZONAS', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '1.800',
    margem: '2 pontos', confianca: '95%', contratante: 'REDE AMAZÔNICA', registro: 'AM-04805/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-amazonas-outubro-2026/',
    itens: [
      { nome: 'OMAR AZIZ', partido: 'PSD', pct: 40, foto: 'omar-aziz' },
      { nome: 'PROFESSORA MARIA DO CARMO', partido: 'PL', pct: 25, foto: 'professora-maria-do-carmo' },
      { nome: 'ROBERTO CIDADE', partido: 'UNIÃO', pct: 24, foto: 'roberto-cidade' },
      { nome: 'DAVID ALMEIDA', partido: 'AVANTE', pct: 11, foto: 'david-almeida' },
      { nome: 'CABO DACIOLO', partido: 'MOBILIZA', pct: 0, foto: 'cabo-daciolo' },
      { nome: 'ISAEL MUNDURUKU', partido: 'REDE', pct: 0, foto: 'tse-am-isael-munduruku' },
      { nome: 'GILBERTO VASCONCELOS', partido: 'PSTU', pct: 0, foto: 'tse-am-gilberto-vasconcelos' },
    ] },
  { id: 'realtime-am-gov-2026-10-02', uf: 'am', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'REAL TIME BIG DATA', divulgacao: '2 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'AMAZONAS', turno: 'VOTOS VÁLIDOS', campo: '28/09 a 01/10/2026', entrevistas: '1.600',
    margem: '2 pontos', confianca: '95%', contratante: '3 PODERES MÍDIA E COMUNICAÇÃO', registro: 'AM-07297/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/real-time-big-data-governador-senador-amazonas-outubro-2026/',
    itens: [
      { nome: 'OMAR AZIZ', partido: 'PSD', pct: 38, foto: 'omar-aziz' },
      { nome: 'ROBERTO CIDADE', partido: 'UNIÃO', pct: 25, foto: 'roberto-cidade' },
      { nome: 'PROFESSORA MARIA DO CARMO', partido: 'PL', pct: 25, foto: 'professora-maria-do-carmo' },
      { nome: 'DAVID ALMEIDA', partido: 'AVANTE', pct: 9, foto: 'david-almeida' },
      { nome: 'CABO DACIOLO', partido: 'MOBILIZA', pct: 2, foto: 'cabo-daciolo' },
      { nome: 'OUTROS', pct: 1, tipo: 'outro' },
    ] },

  // ---------------- PARÁ ----------------
  { id: 'realtime-pa-gov-2026-09-28', uf: 'pa', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'REAL TIME BIG DATA', divulgacao: '28 DE SETEMBRO',
    cargo: 'GOVERNADOR', local: 'PARÁ', turno: '1º TURNO', campo: '23 a 26/09/2026', entrevistas: '1.600',
    margem: '2 pontos', confianca: '95%', contratante: 'REAL TIME BIG DATA (RECURSOS PRÓPRIOS)', registro: 'PA-09993/2026',
    fonteUrl: 'https://www.cnnbrasil.com.br/eleicoes/real-time-big-data-no-pa-hana-soma-44-dr-daniel-tem-37-no-1o-turno/',
    itens: [
      { nome: 'HANA GHASSAN', partido: 'MDB', pct: 44, foto: 'hana-ghassan' },
      { nome: 'DR. DANIEL', partido: 'PODEMOS', pct: 37, foto: 'dr-daniel' },
      { nome: 'ARACELI', partido: 'PSOL', pct: 2, foto: 'araceli' },
      { nome: 'RUTH REIS', partido: 'DEMOCRATA', pct: 1, foto: 'tse-pa-ruth-reis' },
      { nome: 'WELL MACEDO', partido: 'PSTU', pct: 1, foto: 'tse-pa-well-macedo' },
      { nome: 'GAL LEITE', partido: 'UP', pct: 1, foto: 'tse-pa-gal-leite' },
      _IND(9), _BN(7),
    ] },
  { id: 'quaest-pa-gov-2026-10-03', uf: 'pa', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'PARÁ', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '1.800',
    margem: '2 pontos', confianca: '95%', contratante: 'TV LIBERAL', registro: 'PA-04580/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-para-outubro-2026/',
    itens: [
      { nome: 'DR. DANIEL', partido: 'PODEMOS', pct: 57, foto: 'dr-daniel' },
      { nome: 'HANA GHASSAN', partido: 'MDB', pct: 40, foto: 'hana-ghassan' },
      { nome: 'ARACELI', partido: 'PSOL', pct: 2, foto: 'araceli' },
      { nome: 'RUTH REIS', partido: 'DEMOCRATA', pct: 1, foto: 'tse-pa-ruth-reis' },
      { nome: 'GAL LEITE', partido: 'UP', pct: 0, foto: 'tse-pa-gal-leite' },
      { nome: 'WELL MACEDO', partido: 'PSTU', pct: 0, foto: 'tse-pa-well-macedo' },
    ] },

  // ---------------- MARANHÃO ----------------
  { id: 'quaest-ma-gov-2026-10-03', uf: 'ma', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'MARANHÃO', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '2.004',
    margem: '2 pontos', confianca: '95%', contratante: 'TV MIRANTE', registro: 'MA-00831/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-maranhao-outubro-2026/',
    itens: [
      { nome: 'EDUARDO BRAIDE', partido: 'PSD', pct: 52, foto: 'eduardo-braide' },
      { nome: 'ORLEANS BRANDÃO', partido: 'MDB', pct: 35, foto: 'tse-ma-orleans-brandao' },
      { nome: 'FELIPE CAMARÃO', partido: 'PT', pct: 10, foto: 'felipe-camarao' },
      { nome: 'ROBERTO ROCHA', partido: 'PRTB', pct: 2, foto: 'roberto-rocha' },
      { nome: 'ANDRÉ LUIS', partido: 'MISSÃO', pct: 1, foto: 'tse-ma-andre-luis' },
      { nome: 'REGINALDO LIMA', partido: 'PCB', pct: 0, foto: 'tse-ma-reginaldo-lima' },
      { nome: 'DIMAS CASSIMIRO', partido: 'PCO', pct: 0, foto: 'tse-ma-dimas-cassimiro' },
      { nome: 'SAULO ARCANGELI', partido: 'PSTU', pct: 0, foto: 'tse-ma-saulo-arcangeli' },
    ] },

  // ---------------- PIAUÍ ----------------
  { id: 'datafolha-pi-gov-2026-10-03', uf: 'pi', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'PIAUÍ', turno: 'VOTOS VÁLIDOS', campo: '01 a 03/10/2026', entrevistas: '1.564',
    margem: '2 pontos', confianca: '95%', contratante: 'TV RÁDIO CLUBE DE TERESINA', registro: 'PI-05565/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/datafolha-governador-senador-piaui-outubro-2026/',
    itens: [
      { nome: 'RAFAEL FONTELES', partido: 'PT', pct: 67, foto: 'rafael-fonteles' },
      { nome: 'JOEL RODRIGUES', partido: 'PP', pct: 28, foto: 'joel-rodrigues' },
      { nome: 'PROFESSOR GISVALDO', partido: 'PSOL', pct: 2, foto: 'tse-pi-professor-gisvaldo' },
      { nome: 'LUCIA SANTOS', partido: 'PSDB', pct: 1, foto: 'tse-pi-dra-lucia-santos' },
      { nome: 'PROFESSOR JURITY', partido: 'DC', pct: 1, foto: 'tse-pi-professor-jurity' },
      { nome: 'ELIZEU AGUIAR', partido: 'NOVO', pct: 1, foto: 'tse-pi-elizeu-aguiar' },
      { nome: 'SANTIAGO BELIZÁRIO', partido: 'UP', pct: 0, foto: 'tse-pi-santiago-belizario' },
      { nome: 'RAVENA DA INCLUSÃO', partido: 'DEMOCRATA', pct: 0, foto: 'tse-pi-ravenna-da-inclusao' },
    ] },

  // ---------------- ALAGOAS ----------------
  { id: 'quaest-al-gov-2026-10-03', uf: 'al', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'ALAGOAS', turno: 'VOTOS VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '1.800',
    margem: '2 pontos', confianca: '95%', contratante: 'TV ASA BRANCA ALAGOAS', registro: 'AL-09692/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-alagoas-outubro-2026/',
    itens: [
      { nome: 'RENAN FILHO', partido: 'MDB', pct: 50, foto: 'renan-filho' },
      { nome: 'JHC', partido: 'PSDB', pct: 49, foto: 'jhc' },
      { nome: 'LENILDA LUNA', partido: 'UP', pct: 1, foto: 'tse-al-lenilda-luna' },
      { nome: 'MÁRCIO JAMBO', partido: 'DEMOCRATA', pct: 0, foto: 'tse-al-marcio-jambo' },
    ] },
  { id: 'realtime-al-gov-2026-10-02', uf: 'al', creditoFotos: 'fotos: Wikimedia Commons e TSE (licenças Creative Commons)', instituto: 'REAL TIME BIG DATA', divulgacao: '2 DE OUTUBRO',
    cargo: 'GOVERNADOR', local: 'ALAGOAS', turno: 'VOTOS VÁLIDOS', campo: '28/09 a 01/10/2026', entrevistas: '1.600',
    margem: '2 pontos', confianca: '95%', contratante: '3 PODERES MÍDIA E COMUNICAÇÃO', registro: 'AL-01185/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/real-time-big-data-governador-senador-alagoas-outubro-2026/',
    itens: [
      { nome: 'RENAN FILHO', partido: 'MDB', pct: 52, foto: 'renan-filho' },
      { nome: 'JHC', partido: 'PSDB', pct: 48, foto: 'jhc' },
      { nome: 'LENILDA LUNA', partido: 'UP', pct: 0, foto: 'tse-al-lenilda-luna' },
      { nome: 'MÁRCIO JAMBO', partido: 'DEMOCRATA', pct: 0, foto: 'tse-al-marcio-jambo' },
    ] },
  // ================= SENADO (2 vagas; cada eleitor vota em 2 — percentuais somam ~200%) =================
  { id: 'datafolha-ce-sen-2026-10-03', uf: 'ce', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'CEARÁ', turno: '2 VAGAS · VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '1.560',
    margem: '2 pontos', confianca: '95%', contratante: 'O POVO', registro: 'CE-09234/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/datafolha-governador-senador-ceara-outubro-2026/',
    itens: [
      { nome: 'CID GOMES', partido: 'PSB', pct: 31, foto: 'tse-sen-ce-cid-gomes' },
      { nome: 'LUIZIANNE LINS', partido: 'REDE', pct: 28, foto: 'tse-sen-ce-luizianne' },
      { nome: 'CAPITÃO WAGNER', partido: 'UNIÃO', pct: 23, foto: 'tse-sen-ce-capitao-wagner' },
      { nome: 'ALCIDES FERNANDES', partido: 'PL', pct: 14, foto: 'tse-sen-ce-alcides-fernandes' },
      { nome: 'CATARINA MATOS', partido: 'UP', pct: 1, foto: 'tse-sen-ce-catarina-matos' },
      { nome: 'GUILHERME TEOPHILO', partido: 'NOVO', pct: 1, foto: 'tse-sen-ce-guilherme-theophilo' },
      { nome: 'REGINALDO FERREIRA', partido: 'PSTU', pct: 1, foto: 'tse-sen-ce-reginaldo' },
      { nome: 'LINO ALVES', partido: 'PCO', pct: 1, foto: 'tse-sen-ce-lino-alves' },
    ] },
  { id: 'quaest-ce-sen-2026-10-03', uf: 'ce', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'CEARÁ', turno: '2 VAGAS · VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '2.004',
    margem: '2 pontos', confianca: '95%', contratante: 'TV VERDES MARES', registro: 'CE-04790/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-ceara-outubro-2026/',
    itens: [
      { nome: 'CID GOMES', partido: 'PSB', pct: 32, foto: 'tse-sen-ce-cid-gomes' },
      { nome: 'LUIZIANNE LINS', partido: 'REDE', pct: 27, foto: 'tse-sen-ce-luizianne' },
      { nome: 'CAPITÃO WAGNER', partido: 'UNIÃO', pct: 26, foto: 'tse-sen-ce-capitao-wagner' },
      { nome: 'ALCIDES FERNANDES', partido: 'PL', pct: 13, foto: 'tse-sen-ce-alcides-fernandes' },
      { nome: 'CATARINA MATOS', partido: 'UP', pct: 1, foto: 'tse-sen-ce-catarina-matos' },
      { nome: 'GUILHERME TEOPHILO', partido: 'NOVO', pct: 1, foto: 'tse-sen-ce-guilherme-theophilo' },
      { nome: 'LINO ALVES', partido: 'PCO', pct: 0, foto: 'tse-sen-ce-lino-alves' },
      { nome: 'REGINALDO FERREIRA', partido: 'PSTU', pct: 0, foto: 'tse-sen-ce-reginaldo' },
    ] },
  { id: 'datafolha-sp-sen-2026-10-01', uf: 'sp', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '1º DE OUTUBRO',
    cargo: 'SENADO', local: 'SÃO PAULO', turno: '2 VAGAS', campo: '28/09 a 01/10/2026', entrevistas: '1.610',
    margem: '2 pontos', confianca: '95%', contratante: 'FOLHA DE S.PAULO E GLOBO', registro: 'SP-01367/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/datafolha-senador-sao-paulo-outubro-2026/',
    itens: [
      { nome: 'MARINA SILVA', partido: 'REDE', pct: 16, foto: 'tse-sen-sp-marina-silva' },
      { nome: 'ANDRÉ DO PRADO', partido: 'PL', pct: 15, foto: 'tse-sen-sp-andre-do-prado' },
      { nome: 'SIMONE TEBET', partido: 'PSB', pct: 15, foto: 'tse-sen-sp-simone-tebet' },
      { nome: 'GUILHERME DERRITE', partido: 'PP', pct: 14, foto: 'tse-sen-sp-guilherme-derrite' },
      { nome: 'GERALDO RUFINO', partido: 'PODEMOS', pct: 2, foto: 'tse-sen-sp-geraldo-rufino' },
      { nome: 'MARCIO ALVES', partido: 'UP', pct: 2, foto: 'tse-sen-sp-marcio-alves' },
      { nome: 'SONINHA FRANCINE', partido: 'CIDADANIA', pct: 2, foto: 'tse-sen-sp-soninha-francine' },
      { nome: 'MAÍRA DE SOUZA', partido: 'UP', pct: 2, foto: 'tse-sen-sp-maira-de-souza' },
      { nome: 'GUTO SCHIAVETTO', partido: 'MISSÃO', pct: 2, foto: 'tse-sen-sp-guto-schiavetto' },
      { nome: 'DRA ELIANA FERREIRA', partido: 'PSTU', pct: 1, foto: 'tse-sen-sp-dra-eliana-ferreira' },
      { nome: 'WILLIAM TEIXEIRA', partido: 'AGIR', pct: 1, foto: 'tse-sen-sp-william-teixeira' },
      { nome: 'EDNELSON CESARETTI', partido: 'PCO', pct: 1, foto: 'tse-sen-sp-ednelson-cesaretti' },
      { nome: 'PETTER MAAHS', partido: 'PCB', pct: 0, foto: 'tse-sen-sp-petter-maahs' },
      { nome: 'WELLER GONÇALVES', partido: 'PSTU', pct: 0, foto: 'tse-sen-sp-weller-goncalves' },
      { nome: 'RICARDO SALLES', partido: 'NOVO', pct: 2, foto: 'tse-sen-sp-salles' },
      _IND(12), _BN(12),
    ] },
  { id: 'quaest-sp-sen-2026-10-03', uf: 'sp', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'SÃO PAULO', turno: '2 VAGAS · VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '3.702',
    margem: '2 pontos', confianca: '95%', contratante: 'TV GLOBO', registro: 'SP-04726/2026',
    fonteUrl: 'https://www.infomoney.com.br/politica/quaest-derrite-marina-tebet-e-andre-do-prado-empatam-pela-disputa-do-senado-em-sp/',
    itens: [
      { nome: 'GUILHERME DERRITE', partido: 'PP', pct: 25, foto: 'tse-sen-sp-guilherme-derrite' },
      { nome: 'ANDRÉ DO PRADO', partido: 'PL', pct: 23, foto: 'tse-sen-sp-andre-do-prado' },
      { nome: 'MARINA SILVA', partido: 'REDE', pct: 22, foto: 'tse-sen-sp-marina-silva' },
      { nome: 'SIMONE TEBET', partido: 'PSB', pct: 22, foto: 'tse-sen-sp-simone-tebet' },
      { nome: 'OUTROS', pct: 8, tipo: 'outro' },
    ] },
  { id: 'datafolha-rj-sen-2026-10-03', uf: 'rj', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'RIO DE JANEIRO', turno: '2 VAGAS · VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '2.010',
    margem: '2 pontos', confianca: '95%', contratante: 'FOLHA DE S.PAULO E REDE GLOBO', registro: 'RJ-01334/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/datafolha-governador-senador-rio-de-janeiro-outubro-2026-2/',
    itens: [
      { nome: 'BENEDITA DA SILVA', partido: 'PT', pct: 26, foto: 'tse-sen-rj-benedita-da-silva' },
      { nome: 'CARLOS JORDY', partido: 'PL', pct: 19, foto: 'tse-sen-rj-carlos-jordy' },
      { nome: 'CARLOS PORTINHO', partido: 'PL', pct: 18, foto: 'tse-sen-rj-carlos-portinho' },
      { nome: 'PEDRO PAULO', partido: 'PSD', pct: 13, foto: 'tse-sen-rj-pedro-paulo' },
      { nome: 'MONICA BENICIO', partido: 'PSOL', pct: 9, foto: 'tse-sen-rj-monica-benicio' },
      { nome: 'MARCELO CRIVELLA', partido: 'REPUBLICANOS', pct: 6, foto: 'tse-sen-rj-marcelo-crivella' },
      { nome: 'WAGUINHO', partido: 'REPUBLICANOS', pct: 3, foto: 'tse-sen-rj-waguinho' },
      { nome: 'MARCOS DIAS', partido: 'PODEMOS', pct: 2, foto: 'tse-sen-rj-marcos-dias' },
      { nome: 'LUCIANO MATTOS', partido: 'PRTB', pct: 1, foto: 'tse-sen-rj-luciano-mattos' },
      { nome: 'HELIO SECCO', partido: 'MISSÃO', pct: 1, foto: 'tse-sen-rj-helio-secco' },
      { nome: 'PAULA FALCÃO', partido: 'PSTU', pct: 1, foto: 'tse-sen-rj-paula-falcao' },
      { nome: 'MICHELLY XAVIER', partido: 'UP', pct: 1, foto: 'tse-sen-rj-michelly-xavier' },
      { nome: 'LUIZ EUGENIO', partido: 'PCO', pct: 0, foto: 'tse-sen-rj-luiz-eugenio' },
      { nome: 'Ó CLEMENTE', partido: 'DEMOCRATA', pct: 0, foto: 'tse-sen-rj-o-clemente' },
      { nome: 'VINICIUS BENEVIDES', partido: 'UP', pct: 0, foto: 'tse-sen-rj-vinicius-benevides' },
    ] },
  { id: 'quaest-rj-sen-2026-09-29', uf: 'rj', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'QUAEST', divulgacao: '29 DE SETEMBRO',
    cargo: 'SENADO', local: 'RIO DE JANEIRO', turno: '2 VAGAS', campo: '25 a 28/09/2026', entrevistas: '1.302',
    margem: '3 pontos', confianca: '95%', contratante: 'TV GLOBO', registro: 'RJ-04419/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-rio-de-janeiro-setembro-2026-3/',
    itens: [
      { nome: 'BENEDITA DA SILVA', partido: 'PT', pct: 15, foto: 'tse-sen-rj-benedita-da-silva' },
      { nome: 'CARLOS JORDY', partido: 'PL', pct: 15, foto: 'tse-sen-rj-carlos-jordy' },
      { nome: 'CARLOS PORTINHO', partido: 'PL', pct: 15, foto: 'tse-sen-rj-carlos-portinho' },
      { nome: 'MARCELO CRIVELLA', partido: 'REPUBLICANOS', pct: 7, foto: 'tse-sen-rj-marcelo-crivella' },
      { nome: 'PEDRO PAULO', partido: 'PSD', pct: 7, foto: 'tse-sen-rj-pedro-paulo' },
      { nome: 'MONICA BENICIO', partido: 'PSOL', pct: 6, foto: 'tse-sen-rj-monica-benicio' },
      { nome: 'WAGUINHO', partido: 'REPUBLICANOS', pct: 2, foto: 'tse-sen-rj-waguinho' },
      { nome: 'MICHELLY XAVIER', partido: 'UP', pct: 1, foto: 'tse-sen-rj-michelly-xavier' },
      { nome: 'MARCOS DIAS', partido: 'PODEMOS', pct: 1, foto: 'tse-sen-rj-marcos-dias' },
      { nome: 'HELIO SECCO', partido: 'MISSÃO', pct: 0, foto: 'tse-sen-rj-helio-secco' },
      { nome: 'PAULA FALCÃO', partido: 'PSTU', pct: 0, foto: 'tse-sen-rj-paula-falcao' },
      { nome: 'VINICIUS BENEVIDES', partido: 'UP', pct: 0, foto: 'tse-sen-rj-vinicius-benevides' },
      { nome: 'LUCIANO MATTOS', partido: 'PRTB', pct: 0, foto: 'tse-sen-rj-luciano-mattos' },
      { nome: 'LUIZ EUGENIO', partido: 'PCO', pct: 0, foto: 'tse-sen-rj-luiz-eugenio' },
      { nome: 'Ó CLEMENTE', partido: 'DEMOCRATA', pct: 0, foto: 'tse-sen-rj-o-clemente' },
      _IND(9), _BN(22),
    ] },
  { id: 'datafolha-mg-sen-2026-10-01', uf: 'mg', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '1º DE OUTUBRO',
    cargo: 'SENADO', local: 'MINAS GERAIS', turno: '2 VAGAS', campo: '28/09 a 01/10/2026', entrevistas: '1.204',
    margem: '3 pontos', confianca: '95%', contratante: 'FOLHA DE S.PAULO E REDE GLOBO', registro: 'MG-09729/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/datafolha-governador-senado-minas-gerais-outubro-2026/',
    itens: [
      { nome: 'MARÍLIA CAMPOS', partido: 'PT', pct: 13, foto: 'tse-sen-mg-marilia-campos' },
      { nome: 'AÉCIO NEVES', partido: 'PSDB', pct: 11, foto: 'tse-sen-mg-aecio-neves' },
      { nome: 'CARLOS VIANA', partido: 'PSD', pct: 11, foto: 'tse-sen-mg-carlos-viana' },
      { nome: 'DOMINGOS SÁVIO', partido: 'PL', pct: 9, foto: 'tse-sen-mg-domingos-savio' },
      { nome: 'MARCELO ARO', partido: 'PP', pct: 6, foto: 'tse-sen-mg-marcelo-aro' },
      { nome: 'ÁUREA CAROLINA', partido: 'PSOL', pct: 5, foto: 'tse-sen-mg-aurea-carolina' },
      { nome: 'ANA LUIZA DO MLB', partido: 'UP', pct: 2, foto: 'tse-sen-mg-ana-luiza-do-mlb' },
      { nome: 'MARCO ANTÔNIO SUPERMAN', partido: 'NOVO', pct: 2, foto: 'tse-sen-mg-marco-antonio-superman' },
      { nome: 'MANOEL CARVALHO', partido: 'MDB', pct: 1, foto: 'tse-sen-mg-manoel-carvalho' },
      { nome: 'VICTÓRIA MELLO VIC', partido: 'PSTU', pct: 1, foto: 'tse-sen-mg-victoria-mello-vic' },
      { nome: 'ARCANJO PIMENTA', partido: 'MDB', pct: 1, foto: 'tse-sen-mg-arcanjo-pimenta' },
      { nome: 'CARLIN MOURA', partido: 'AVANTE', pct: 1, foto: 'tse-sen-mg-carlin-moura' },
      { nome: 'TIÃO PESSOA', partido: 'PCO', pct: 1, foto: 'tse-sen-mg-tiao-pessoa' },
      { nome: 'JUIZ RAMON MOREIRA', partido: 'DC', pct: 1, foto: 'tse-sen-mg-juiz-ramon-moreira' },
      { nome: 'FIDÉLIS ALCÂNTARA', partido: 'UP', pct: 0, foto: 'tse-sen-mg-fidelis-alcantara' },
      { nome: 'JORDANO METALÚRGICO', partido: 'PSTU', pct: 0, foto: 'tse-sen-mg-jordano-metalurgico' },
      _IND(20), _BN(15),
    ] },
  { id: 'quaest-mg-sen-2026-09-29', uf: 'mg', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'QUAEST', divulgacao: '29 DE SETEMBRO',
    cargo: 'SENADO', local: 'MINAS GERAIS', turno: '2 VAGAS', campo: '25 a 28/09/2026', entrevistas: '1.506',
    margem: '3 pontos', confianca: '95%', contratante: 'TV GLOBO', registro: 'MG-02019/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-minas-gerais-setembro-2026-3/',
    itens: [
      { nome: 'DOMINGOS SÁVIO', partido: 'PL', pct: 14, foto: 'tse-sen-mg-domingos-savio' },
      { nome: 'MARÍLIA CAMPOS', partido: 'PT', pct: 13, foto: 'tse-sen-mg-marilia-campos' },
      { nome: 'CARLOS VIANA', partido: 'PSD', pct: 12, foto: 'tse-sen-mg-carlos-viana' },
      { nome: 'AÉCIO NEVES', partido: 'PSDB', pct: 12, foto: 'tse-sen-mg-aecio-neves' },
      { nome: 'MARCELO ARO', partido: 'PP', pct: 6, foto: 'tse-sen-mg-marcelo-aro' },
      { nome: 'MARCO ANTÔNIO SUPERMAN', partido: 'NOVO', pct: 4, foto: 'tse-sen-mg-marco-antonio-superman' },
      { nome: 'ÁUREA CAROLINA', partido: 'PSOL', pct: 4, foto: 'tse-sen-mg-aurea-carolina' },
      _IND(18), _BN(17),
    ] },
  { id: 'quaest-am-sen-2026-10-03', uf: 'am', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'AMAZONAS', turno: '2 VAGAS', campo: '02 e 03/10/2026', entrevistas: '1.800',
    margem: '2 pontos', confianca: '95%', contratante: 'REDE AMAZÔNICA', registro: 'AM-04805/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-amazonas-outubro-2026/',
    itens: [
      { nome: 'EDUARDO BRAGA', partido: 'MDB', pct: 27, foto: 'tse-sen-am-eduardo-braga' },
      { nome: 'CAPITÃO ALBERTO NETO', partido: 'PL', pct: 18, foto: 'tse-sen-am-capitao-alberto-neto' },
      { nome: 'PLINIO VALÉRIO', partido: 'PSDB', pct: 16, foto: 'tse-sen-am-plinio-valerio' },
      { nome: 'WILSON LIMA', partido: 'UNIÃO', pct: 12, foto: 'tse-sen-am-wilson-lima' },
      { nome: 'ISMAEL MUNDURUKU', partido: 'REDE', pct: 1, foto: 'tse-sen-am-ismael-munduruku' },
      { nome: 'PROFESSORA EVANY', partido: 'PSOL', pct: 1, foto: 'tse-sen-am-professora-evany' },
      { nome: 'XUXA DO AMAZONAS', partido: 'MOBILIZA', pct: 0, foto: 'tse-sen-am-xuxa-do-amazonas' },
      { nome: 'DAILSON CORRÊA', partido: 'DC', pct: 0, foto: 'tse-sen-am-dailson-correa' },
      { nome: 'EVANDRO DE OLIVEIRA', partido: 'PSTU', pct: 0, foto: 'tse-sen-am-evandro-de-oliveira' },
      _IND(10), _BN(15),
    ] },
  { id: 'realtime-am-sen-2026-10-02', uf: 'am', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'REAL TIME BIG DATA', divulgacao: '2 DE OUTUBRO',
    cargo: 'SENADO', local: 'AMAZONAS', turno: '2 VAGAS', campo: '28/09 a 01/10/2026', entrevistas: '1.600',
    margem: '2 pontos', confianca: '95%', contratante: '3 PODERES MÍDIA E COMUNICAÇÃO', registro: 'AM-07297/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/real-time-big-data-governador-senador-amazonas-outubro-2026/',
    itens: [
      { nome: 'CAPITÃO ALBERTO NETO', partido: 'PL', pct: 25, foto: 'tse-sen-am-capitao-alberto-neto' },
      { nome: 'WILSON LIMA', partido: 'UNIÃO', pct: 19, foto: 'tse-sen-am-wilson-lima' },
      { nome: 'PLINIO VALÉRIO', partido: 'PSDB', pct: 19, foto: 'tse-sen-am-plinio-valerio' },
      { nome: 'EDUARDO BRAGA', partido: 'MDB', pct: 19, foto: 'tse-sen-am-eduardo-braga' },
      { nome: 'XUXA DO AMAZONAS', partido: 'MOBILIZA', pct: 4, foto: 'tse-sen-am-xuxa-do-amazonas' },
      { nome: 'ISMAEL MUNDURUKU', partido: 'REDE', pct: 3, foto: 'tse-sen-am-ismael-munduruku' },
      { nome: 'PROFESSORA EVANY', partido: 'PSOL', pct: 2, foto: 'tse-sen-am-professora-evany' },
      { nome: 'EVANDRO DE OLIVEIRA', partido: 'PSTU', pct: 0, foto: 'tse-sen-am-evandro-de-oliveira' },
      { nome: 'DAILSON CORRÊA', partido: 'DC', pct: 0, foto: 'tse-sen-am-dailson-correa' },
      _IND(5), _BN(4),
    ] },
  { id: 'realtime-pa-sen-2026-09-28', uf: 'pa', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'REAL TIME BIG DATA', divulgacao: '28 DE SETEMBRO',
    cargo: 'SENADO', local: 'PARÁ', turno: '2 VAGAS', campo: '23 a 26/09/2026', entrevistas: '1.600',
    margem: '2 pontos', confianca: '95%', contratante: 'REAL TIME BIG DATA (RECURSOS PRÓPRIOS)', registro: 'PA-09993/2026',
    fonteUrl: 'https://www.cartacapital.com.br/politica/real-time-helder-lidera-para-o-senado-no-para-com-20-pontos-de-vantagem-sobre-bolsonarista/',
    itens: [
      { nome: 'HELDER BARBALHO', partido: 'MDB', pct: 36, foto: 'tse-sen-pa-helder' },
      { nome: 'DELEGADO ÉDER MAURO', partido: 'PL', pct: 16, foto: 'tse-sen-pa-delegado-eder-mauro' },
      { nome: 'CHICÃO', partido: 'UNIÃO', pct: 16, foto: 'tse-sen-pa-chicao' },
      { nome: 'ZEQUINHA MARINHO', partido: 'PODEMOS', pct: 13, foto: 'tse-sen-pa-zequinha-marinho' },
      { nome: 'CELSO SABINO', partido: 'PDT', pct: 10, foto: 'tse-sen-pa-celso-sabino' },
      { nome: 'LÍVIA NORONHA', partido: 'SOLIDARIEDADE', pct: 3, foto: 'tse-sen-pa-livia-noronha' },
      { nome: 'MARCELINO CONTI', partido: 'PSOL', pct: 1, foto: 'tse-sen-pa-conti' },
      { nome: 'GIZELLE FREITAS', partido: 'PSOL', pct: 1, foto: 'tse-sen-pa-gizelle-freitas' },
      { nome: 'BRENO GUIMARÃES', partido: 'MOBILIZA', pct: 0, foto: 'tse-sen-pa-breno-guimaraes' },
      { nome: 'CORONEL JONILDO', partido: 'DC', pct: 0, foto: 'tse-sen-pa-coronel-jonildo' },
      { nome: 'EDLAINE RODRIGUES', partido: 'DEMOCRATA', pct: 0, foto: 'tse-sen-pa-edlaine-rodrigues' },
      { nome: 'FERNANDA LOPES', partido: 'UP', pct: 0, foto: 'tse-sen-pa-fernanda-lopes' },
      _IND(3), _BN(2),
    ] },
  { id: 'quaest-pa-sen-2026-10-03', uf: 'pa', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'PARÁ', turno: '2 VAGAS · VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '1.800',
    margem: '2 pontos', confianca: '95%', contratante: 'TV LIBERAL', registro: 'PA-04580/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-para-outubro-2026/',
    itens: [
      { nome: 'HELDER BARBALHO', partido: 'MDB', pct: 28, foto: 'tse-sen-pa-helder' },
      { nome: 'DELEGADO ÉDER MAURO', partido: 'PL', pct: 24, foto: 'tse-sen-pa-delegado-eder-mauro' },
      { nome: 'CHICÃO', partido: 'UNIÃO', pct: 20, foto: 'tse-sen-pa-chicao' },
      { nome: 'ZEQUINHA MARINHO', partido: 'PODEMOS', pct: 17, foto: 'tse-sen-pa-zequinha-marinho' },
      { nome: 'CELSO SABINO', partido: 'PDT', pct: 8, foto: 'tse-sen-pa-celso-sabino' },
      { nome: 'GIZELLE FREITAS', partido: 'PSOL', pct: 1, foto: 'tse-sen-pa-gizelle-freitas' },
      { nome: 'LÍVIA NORONHA', partido: 'SOLIDARIEDADE', pct: 1, foto: 'tse-sen-pa-livia-noronha' },
      { nome: 'CORONEL JONILDO', partido: 'DC', pct: 1, foto: 'tse-sen-pa-coronel-jonildo' },
      { nome: 'FERNANDA LOPES', partido: 'UP', pct: 0, foto: 'tse-sen-pa-fernanda-lopes' },
      { nome: 'MARCELINO CONTI', partido: 'PSOL', pct: 0, foto: 'tse-sen-pa-conti' },
      { nome: 'EDLAINE RODRIGUES', partido: 'DEMOCRATA', pct: 0, foto: 'tse-sen-pa-edlaine-rodrigues' },
      { nome: 'BRENO GUIMARÃES', partido: 'MOBILIZA', pct: 0, foto: 'tse-sen-pa-breno-guimaraes' },
    ] },
  { id: 'quaest-ma-sen-2026-10-03', uf: 'ma', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'MARANHÃO', turno: '2 VAGAS · VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '2.004',
    margem: '2 pontos', confianca: '95%', contratante: 'TV MIRANTE', registro: 'MA-00831/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-maranhao-outubro-2026/',
    itens: [
      { nome: 'ROSEANA SARNEY', partido: 'MDB', pct: 25, foto: 'tse-sen-ma-roseana-sarney' },
      { nome: 'ANDRÉ FUFUCA', partido: 'PP', pct: 23, foto: 'tse-sen-ma-fufuca' },
      { nome: 'LAHESIO BONFIM', partido: 'NOVO', pct: 18, foto: 'tse-sen-ma-lahesio-bonfim' },
      { nome: 'ELIZIANE GAMA', partido: 'PT', pct: 16, foto: 'tse-sen-ma-eliziane-gama' },
      { nome: 'WEVERTON ROCHA', partido: 'PDT', pct: 12, foto: 'tse-sen-ma-weverton-rocha' },
      { nome: 'CIDÔNIO GONÇALVES', partido: 'PL', pct: 4, foto: 'tse-sen-ma-cidonio-goncalves' },
      { nome: 'HILTON GONÇALO', partido: 'MOBILIZA', pct: 2, foto: 'tse-sen-ma-dr-hilton-goncalo' },
      { nome: 'SIMPLÍCIO ARAÚJO', partido: 'DC', pct: 0, foto: 'tse-sen-ma-simplicio-araujo' },
      { nome: 'RAIMUNDO MOREIRA', partido: 'PCB', pct: 0, foto: 'tse-sen-ma-raimundo-moreira' },
      { nome: 'WILSON LEITE', partido: 'PSTU', pct: 0, foto: 'tse-sen-ma-wilson-leite' },
      { nome: 'ENILTON RODRIGUES', partido: 'PSOL', pct: 0, foto: 'tse-sen-ma-enilton-rodrigues' },
    ] },
  { id: 'datafolha-pi-sen-2026-10-03', uf: 'pi', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'DATAFOLHA', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'PIAUÍ', turno: '2 VAGAS · VÁLIDOS', campo: '01 a 03/10/2026', entrevistas: '1.564',
    margem: '2 pontos', confianca: '95%', contratante: 'TV RÁDIO CLUBE DE TERESINA', registro: 'PI-05565/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/datafolha-governador-senador-piaui-outubro-2026/',
    itens: [
      { nome: 'MARCELO CASTRO', partido: 'MDB', pct: 28, foto: 'tse-sen-pi-marcelo-castro' },
      { nome: 'CIRO NOGUEIRA', partido: 'PP', pct: 26, foto: 'tse-sen-pi-ciro-nogueira' },
      { nome: 'JÚLIO CÉSAR', partido: 'PSD', pct: 25, foto: 'tse-sen-pi-julio-cesar-o-julim-do-lula' },
      { nome: 'TIAGO JUNQUEIRA', partido: 'PL', pct: 9, foto: 'tse-sen-pi-tiago-junqueira' },
      { nome: 'MAJOR PAULO ROBERTO', partido: 'MOBILIZA', pct: 1, foto: 'tse-sen-pi-major-paulo-roberto' },
      { nome: 'JORGE LOPES', partido: 'PSDB', pct: 1, foto: 'tse-sen-pi-jorge-lopes' },
      { nome: 'PEDRO LAURENTINO', partido: 'UP', pct: 1, foto: 'tse-sen-pi-pedro-laurentino' },
      { nome: 'IRMÃO EVANDRO MARQUES', partido: 'DC', pct: 1, foto: 'tse-sen-pi-irmao-evandro-marques' },
      { nome: 'MARIA MADALENA NUNES', partido: 'PSOL', pct: 1, foto: 'tse-sen-pi-maria-madalena-nunes' },
      { nome: 'FRANCINALDO LEÃO', partido: 'PSOL', pct: 1, foto: 'tse-sen-pi-francinaldo-leao' },
      { nome: 'DIONÍSIO CARVALHO', partido: 'DC', pct: 1, foto: 'tse-sen-pi-dionisio-carvalho' },
      { nome: 'DANNIEL ROCHA', partido: 'PSTU', pct: 1, foto: 'tse-sen-pi-danniel-rocha' },
      { nome: 'JARDENYA BEZERRA', partido: 'DEMOCRATA', pct: 0, foto: 'tse-sen-pi-jardenya-bezerra' },
      { nome: 'CLOVES JOSÉ', partido: 'PCO', pct: 0, foto: 'tse-sen-pi-cloves-jose' },
      { nome: 'MISSIONÁRIO EVANDRO CRAVEIRO', partido: 'DEMOCRATA', pct: 0, foto: 'tse-sen-pi-missionario-evandro-craveiro' },
    ] },
  { id: 'quaest-al-sen-2026-10-03', uf: 'al', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'QUAEST', divulgacao: '3 DE OUTUBRO',
    cargo: 'SENADO', local: 'ALAGOAS', turno: '2 VAGAS · VÁLIDOS', campo: '02 e 03/10/2026', entrevistas: '1.800',
    margem: '2 pontos', confianca: '95%', contratante: 'TV ASA BRANCA ALAGOAS', registro: 'AL-09692/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/quaest-governador-senador-alagoas-outubro-2026/',
    itens: [
      { nome: 'MARINA JHC', partido: 'PSDB', pct: 29, foto: 'tse-sen-al-marina-jhc' },
      { nome: 'ARTHUR LIRA', partido: 'PP', pct: 27, foto: 'tse-sen-al-arthur-lira' },
      { nome: 'RENAN CALHEIROS', partido: 'MDB', pct: 25, foto: 'tse-sen-al-renan' },
      { nome: 'DAVI DAVINO FILHO', partido: 'REPUBLICANOS', pct: 9, foto: 'tse-sen-al-davi-davino-filho' },
      { nome: 'DR. WANDERLEY', partido: 'MDB', pct: 9, foto: 'tse-sen-al-dr-wanderley' },
      { nome: 'MARIEDSON', partido: 'DEMOCRATA', pct: 1, foto: 'tse-sen-al-mariedson' },
      { nome: 'ALEXANDRE FLEMING', partido: 'UP', pct: 0, foto: 'tse-sen-al-alexandre-fleming' },
    ] },
  { id: 'realtime-al-sen-2026-10-02', uf: 'al', creditoFotos: 'fotos: TSE (licença Creative Commons)', instituto: 'REAL TIME BIG DATA', divulgacao: '2 DE OUTUBRO',
    cargo: 'SENADO', local: 'ALAGOAS', turno: '2 VAGAS', campo: '28/09 a 01/10/2026', entrevistas: '1.600',
    margem: '2 pontos', confianca: '95%', contratante: '3 PODERES MÍDIA E COMUNICAÇÃO', registro: 'AL-01185/2026',
    fonteUrl: 'https://www.gazetadopovo.com.br/eleicoes/2026/pesquisa-eleitoral-2026/real-time-big-data-governador-senador-alagoas-outubro-2026/',
    itens: [
      { nome: 'MARINA JHC', partido: 'PSDB', pct: 27, foto: 'tse-sen-al-marina-jhc' },
      { nome: 'RENAN CALHEIROS', partido: 'MDB', pct: 23, foto: 'tse-sen-al-renan' },
      { nome: 'ARTHUR LIRA', partido: 'PP', pct: 22, foto: 'tse-sen-al-arthur-lira' },
      { nome: 'DAVI DAVINO FILHO', partido: 'REPUBLICANOS', pct: 17, foto: 'tse-sen-al-davi-davino-filho' },
      { nome: 'DR. WANDERLEY', partido: 'MDB', pct: 4, foto: 'tse-sen-al-dr-wanderley' },
      { nome: 'ALEXANDRE FLEMING', partido: 'UP', pct: 1, foto: 'tse-sen-al-alexandre-fleming' },
      { nome: 'MARIEDSON', partido: 'DEMOCRATA', pct: 0, foto: 'tse-sen-al-mariedson' },
      _IND(4), _BN(2),
    ] },
];
